server:
  port: 8087
spring:
  datasource:
    initialize: false
    url: ${db.url:jdbc:mysql://containers-us-west-23.railway.app:6820/railway}
    username: ${db.username:root}
    password: ${db.password:V8izmmDtgEczUdsqHqhZ}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: claims-config-service
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

  main:
    allow-bean-definition-overriding: true
webhook_token: LAPH1329@PEQS
token: EAAcfBnBqsxIBADy0RcZAQZBUO2FKPbRr3DrcPZA3wzJZCsYaTW7jPLuk1jbR3B3wqtrSLjeMOMDAVYfy7RaW6VA03VHcnnH0sQ7fRD1WEWZAtVMRiJam6ZB6ZBin0Ri5xhZBRD3CT2xfYCSlndKUuif8gXqs5o9Jq3gFZCZABiElLycoQ8vEnUGMefJ0HTTr3ckXxtVMYMkYu5ZAwhii2OMiufnTmkDXIJ9RVMZD